INSERT INTO kinghost.stginteracoes (protocolo, id_sessao, login_agente, caminho_agentes, fila, caminho_filas, login_cliente, cliente, email, telefone_1, telefone_2, navegador, data_inicio_interacao, data_desvio_interacao, data_resposta_interacao, data_fim_interacao, tempo_atendimento, tempo_espera, status, quantidade_interacoes, quantidade_transferencias, nivel1, nivel2, nivel3, nivel4, nivel5, p1, p2, p3, comentarios, comentarios_2, comentarios_3, autorizacao_requisitada, autorizacao_aceita, autorizacao_erro, boleto, canal, ip, fonte_de_dados, data_criacao_do_arquivo, data_insercao, data_modificacao)
SELECT 
"protocoloXgen" AS protocolo,
"sessionXgen" AS id_sessao,
"analista" AS login_agente, 
NULL AS caminho_agentes,
"filaEscolhida"AS fila,
NULL AS caminho_filas,
"LoginCliente" AS login_cliente, --trocar idCliente por LoginCliente no arquivo recebido
"NomeCliente" AS cliente, --trazer um campo com o nome completo do cliente
"email",
"telefone" AS telefone_1,
CASE WHEN "emailAnalistaDuvidas" LIKE '%@%' THEN NULL ELSE "emailAnalistaDuvidas" END AS telefone_2,
"Navegador" AS navegador,
CAST("dataHora" as TIMESTAMP) AS data_inicio_interacao,
CAST("dataHora" as TIMESTAMP) AS data_desvio_interacao,
CAST("dataHora" as TIMESTAMP) AS data_resposta_interacao,
CAST("dataHoraAtendido" AS TIMESTAMP) AS data_fim_interacao,
"tempoAtendimento" AS tempo_atendimento,
"tempoEsperaAjustado" AS tempo_espera,
"ultimo_status" AS status,
"qtsInteracoes" AS quantidade_interacoes,
"qtsAtendimentos" -1 AS quantidade_transferencias, 
"Nivel1" AS nivel1,
"Nivel2" AS nivel2,
"Nivel3" AS nivel3,
"Nivel4" AS nivel4,
"Nivel5" AS nivel5,
"notaAnalista" AS p1,
"notaSolucao" AS p2,
"notaKing" AS p3,
"comentario" AS comentarios,
NULL AS comentarios_2,
NULL AS comentarios_3,
NULL AS autorizacao_requisitada,
NULL AS autorizacao_aceita,
NULL AS autorizacao_erro,
NULL AS boleto,
"Canal" AS canal,
"IP" AS ip,
'KingHost' AS fonte_de_dados,
CAST("data_criacao_do_arquivo" AS TIMESTAMP) AS data_criacao_do_arquivo,
NOW() - INTERVAL '3 Hour' AS data_insercao,
NOW() - INTERVAL '3 Hour' AS data_modificacao
FROM kinghost.rawdata;