INSERT INTO kinghost.stgclassificacoes (
    	idHistorico,
	idCliente,
	id_sessao,
	servicoLw,
	servicoTipoLw,
    	plano,
	data_hora_historico,
	analista,
	login_cliente,
	nome_cliente,
	canal,
	nivel1,
	nivel2,
	nivel3,
	nivel4,
	nivel5,
	produto,
	setor,
	rede,
	chat_id,
	data_inicio_interacao,
    data_fim_interacao,
	fonte_de_dados,
	data_insercao,
	data_modificacao
) 
SELECT
"IdHistorico" AS idHistorico,
"IdCliente" AS idCliente,
"SessionID" AS id_sessao,
"ServicoLw"	AS servicoLw,
"ServicoTipoLw"	AS servicoTipoLw,
"Plano" AS plano,
CAST("DataHoraHistorico" AS TIMESTAMP) AS data_hora_historico,
"Analista" AS analista,
"LoginCliente" AS login_cliente,
"NomeCliente" nome_cliente,
"Canal" AS canal,
"Servico" AS nivel1,
"Funcionalidade" AS nivel2,
"TipoAtendimento" AS nivel3,
"Motivo" AS nivel4,
"Detalhe" AS nivel5,
NULL AS produto,
"Setor" AS setor, 
"Rede" AS rede,
"ProtocoloXgen" AS chat_id,
NULLIF(CAST("DataInicioAtendimento" AS TEXT), '')::TIMESTAMP AS data_inicio_interacao,
NULLIF(CAST("DataFimAtendimento" AS TEXT), '')::TIMESTAMP AS data_fim_interacao,
'D-1' AS fonte_de_dados,
NOW() AS data_insercao,
NOW() AS data_modificacao
FROM kinghost.rawdata;