INSERT INTO octadesk.s_conversas 
(protocolo,status,nome_solicitante,email_solicitante,telefone_solicitante,organizacao,data_inicio,data_final,tempoemespera,
duracao,responsavel,analista,grupo_responsavel,interacoes,origem_conversa,status_pesquisa,comentario_pesquisa,ticket,fluxo_bots,tags,
tempo_espera_apos_atribuicao,octabsp,id_conversa,numero_conversa,primeira_mensagem_cliente,tamanho_empresa,customfield_v2_cnpj,customfield_v2_motivo_financeiro,
customfield_v2_faturaematraso,cnpj,motivo_financeiro,dialog360,octadesk,socialminer,nomedaempresa,undefined,motivo_de_contato,nome_empresa,email_agente,customfield_nome_contato,
customfield,sitedaempresa,system_information_authorization,system_information_subdomain,system_information_now,divulgacaooctanapratica,customfieldcnpj,melhorhorariooctanapratica,
utm_source,utm_medium,utm_campaign,utm_term,utm_content,hubspotutk,subdominio_octadesk,"cluster",codigo_plano,mrr,data_criacao_ambiente,data_contratacao,
perfil_do_usuario,canal_que_preferem_receber_comunicacoes,temadeinteresse_octanapratica,participante)
SELECT 
    A.protocolo::BIGINT,
    A.status::TEXT,
    A.nome_solicitante::TEXT,
    A.email_solicitante::TEXT,
    REPLACE(A.telefone_solicitante::TEXT, '+','') AS telefone_solicitante,
    A.organizacao::TEXT,
    A.data_inicio::TIMESTAMP,
    A.data_final::TIMESTAMP,
    A.tempoemespera::TEXT,
    A.duracao::TEXT,
    A.responsavel::TEXT,
    A.analista::TEXT,
    A.grupo_responsavel::TEXT,
    NULLIF(A.interacoes::TEXT,'-') AS interacoes,
    REPLACE(A.origem_conversa::TEXT,'+','') AS origem_conversa,
    A.status_pesquisa::TEXT,
    A.comentario_pesquisa::TEXT,
    A.ticket::TEXT,
    A.fluxo_bots::TEXT,
    A.tags::TEXT,
    A.tempo_espera_apos_atribuicao::TEXT,
    NULLIF(A.octabsp::TEXT,'-') AS octabsp,
    A.id_conversa::TEXT,
    A.numero_conversa::TEXT,
    REPLACE(REPLACE(REPLACE(REPLACE(A.primeira_mensagem_cliente::TEXT,'<p>',''),'<br>',''),'</p>',''),'</br>','') AS primeira_mensagem_cliente, 
    A.tamanho_empresa::TEXT,
    A.customfield_v2_cnpj::TEXT,
    A.customfield_v2_motivo_financeiro::TEXT,
    A.customfield_v2_faturaematraso::TEXT,
    A.cnpj::TEXT,
    A.motivo_financeiro::TEXT,
    A.dialog360::TEXT,
    A.octadesk::TEXT,
    A.socialminer::TEXT,
    A.nomedaempresa::TEXT,
    A.undefined::TEXT,
    A.motivo_de_contato::TEXT,
    A.nome_empresa::TEXT,
    A.email_agente::TEXT,
    A.customfield_nome_contato::TEXT,
    A.customfield::TEXT,
    A.sitedaempresa::TEXT,
    A.system_information_authorization::TEXT,
    A.system_information_subdomain::TEXT,
    A.system_information_now::TEXT,
    A.divulgacaooctanapratica::TEXT,
    A.customfieldcnpj::TEXT,
    A.melhorhorariooctanapratica::TEXT,
    A.utm_source::TEXT,
    A.utm_medium::TEXT,
    A.utm_campaign::TEXT,
    A.utm_term::TEXT,
    A.utm_content::TEXT,
    A.hubspotutk::TEXT,
    A.subdominio_octadesk::TEXT,
    A."cluster"::TEXT,
    A.codigo_plano::TEXT,
    A.mrr::TEXT,
    A.data_criacao_ambiente::TEXT,
    A.data_contratacao::TEXT,
    A.perfil_do_usuario::TEXT,
    A.canal_que_preferem_receber_comunicacoes::TEXT,
    A.temadeinteresse_octanapratica::TEXT,
    A.participante::TEXT
FROM 
    octadesk.stg_conversas A
    WHERE NOT EXISTS(SELECT 1 FROM octadesk.s_conversas S WHERE S.protocolo = A.protocolo )

