UPDATE kinghost.chamados AS C
SET 
    idefetivo = SC."IdChamado",
    idincidente = SC."IdIncidente",
    categoriafila = substring(SC."Fila" from '\((.*?)\)'),
    fila = SC."Fila",
    logincliente = SC."LoginCliente",
    abertopor = SC."AbertoPor",
    proprietario = SC."Proprietario",
    equipeproprietaria = SC."EquipeProprietaria",
    assunto = SC."Assunto",
    prioridadeinicial = SC."PrioridadeInicial",
    prioridadefinal = SC."PrioridadeFinal",
    prioridade = SC."Prioridade",
    tipocontato = SC."TipoContato",
    tempoestimado = SC."TempoEstimado",
    tempotrabalhado = SC."TempoTrabalhado",
    status = initcap(substring(SC."Status" from '\w+')),
    razaostatus = SC."RazaoStatus",
    temporestante = SC."TempoRestante",
    datarecebido = to_timestamp(SC."DataRecebido") AT TIME ZONE 'America/Sao_Paulo',
    datainiciado = CAST(SC."DataInicio" AS TIMESTAMP),
    datadevida = to_timestamp(SC."DataRecebido") AT TIME ZONE 'America/Sao_Paulo',
    dataresolvido = CAST(SC."DataResolvido" AS TIMESTAMP),
    agenteultimainteracao = SC."AgenteUltimaInteracao",
    dataultimainteracao = CAST(SC."DataUltimaInteracao" AS TIMESTAMP),
    criador = SC."Criador",
    datacriacao = CAST(SC."DataCriacao" AS TIMESTAMP),
    p1 = SC."P1",
    p2 = SC."P2",
    p3 = SC."P3",
    canal = SC."Canal",
    origem = initcap(substring(SC."Origem" from '\w+')),
    fontedados = 'KingHost',
    quantidadeinteracoes = SC."QuantidadeInteracoesKinghost" + SC."QuantidadeInteracoesCliente",
    temmotivo = SC."TemMotivo",
    temclassificacao = CASE WHEN SC."TemClassificacao" IS NULL THEN 'Não' ELSE SC."TemClassificacao" END,
    nivel1 = SC."Nivel1",
    nivel2 = SC."Nivel2",
    nivel3 = SC."Nivel3",
    nivel4 = NULL,
    nivel5 = NULL,
    inc_ritm_prb = SC."inc_ritm_prb",
    inc = SC."inc",
    ritm = SC."ritm",
    prb = SC."prb",
    transferido = CASE WHEN SC."Transferido" = 0 THEN FALSE ELSE TRUE END,
    recontato = CASE WHEN SC."Recontato" = 0 THEN FALSE ELSE TRUE END,
    respondido = CASE WHEN SC."Respondido" = 0 THEN FALSE ELSE TRUE END,
    reaberto = CASE WHEN SC."Reaberto" = 0 THEN FALSE ELSE TRUE END,
    datamodificacao = NOW(),
    comentarios = SC."Comentario"
FROM kinghost.stgchamados AS SC
WHERE 
    C.idefetivo = SC."IdChamado"
    AND (CAST(SC."DataUltimaInteracao" AS TIMESTAMP) > C.dataultimainteracao OR (C.p1 IS NULL AND SC."P1" IS NOT NULL));