INSERT INTO kinghost.chamadosbacklog (
    idchamado, idefetivo, idincidente, categoriafila, fila, logincliente, abertopor, proprietario, equipeproprietaria, assunto, prioridadeinicial, prioridadefinal, 
    prioridade, tipocontato, tempoestimado, tempotrabalhado, status, razaostatus, temporestante, datarecebido, datainicio, datainiciado, datadevida, dataresolvido, 
    agenteultimainteracao, dataultimainteracao, criador, datacriacao, p1, p2, p3, canal, origem, fontedados, quantidadeinteracoescliente, temmotivo, temclassificacao, nivel1, 
    nivel2, nivel3, nivel4, nivel5, inc_ritm_prb, inc, ritm, prb, transferido, recontato, respondido, reaberto, datainsercao, datamodificacao, comentarios,quantidadeinteracoeskinghost
)
SELECT 
    CAST(SC."IdChamado" AS VARCHAR) AS idchamado,
    SC."IdChamado" AS idefetivo,
    SC."IdIncidente" AS idincidente,
    substring(SC."Fila" from '\((.*?)\)') AS categoriafila,
    SC."Fila" AS fila,
    SC."LoginCliente" AS logincliente,
    SC."AbertoPor" AS abertopor,
    SC."Proprietario" AS proprietario,
    SC."EquipeProprietaria" AS equipeproprietaria,
    SC."Assunto" AS assunto,
    SC."PrioridadeInicial" AS prioridadeinicial,
    SC."PrioridadeFinal" AS prioridadefinal,
    SC."Prioridade" AS prioridade,
    SC."TipoContato" AS tipocontato,
    SC."TempoEstimado" AS tempoestimado,
    SC."TempoTrabalhado" AS tempotrabalhado,
    initcap(substring(SC."Status" from '\w+')) AS status,
    SC."RazaoStatus" AS razaostatus,
    SC."TempoRestante" AS temporestante,
    to_timestamp(SC."DataRecebido") AT TIME ZONE 'America/Sao_Paulo' AS datarecebido,
    NULL AS datainicio,
    CAST(SC."DataInicio" AS TIMESTAMP) AS datainiciado,
    to_timestamp(SC."DataRecebido") AT TIME ZONE 'America/Sao_Paulo' AS datadevida,
    CAST(SC."DataResolvido" AS TIMESTAMP) AS dataresolvido,
    SC."AgenteUltimaInteracao" AS agenteultimainteracao,
    CAST(SC."DataUltimaInteracao" AS TIMESTAMP) AS dataultimainteracao,
    SC."Criador" AS criador,
    CAST(SC."DataCriacao" AS TIMESTAMP) AS datacriacao,
    SC."P1" AS p1,
    SC."P2" AS p2,
    SC."P3" AS p3,
    SC."Canal" AS canal,
    initcap(substring(SC."Origem" from '\w+')) AS origem,
    CAST('KingHost' AS VARCHAR) AS fontedados,
    SC."QuantidadeInteracoesCliente" AS quantidadeinteracoescliente,
    SC."TemMotivo" AS temmotivo,
    CASE WHEN SC."TemClassificacao" IS NULL THEN 'Não' ELSE SC."TemClassificacao" END AS temclassificacao,
    SC."Nivel1" AS nivel1,
    SC."Nivel2" AS nivel2,
    SC."Nivel3" AS nivel3,
    NULL AS nivel4,
    NULL AS nivel5,
    SC."inc_ritm_prb" AS inc_ritm_prb,
    SC."inc" AS inc,
    SC."ritm" AS ritm,
    SC."prb" AS prb,
    CASE WHEN SC."Transferido" = 0 THEN FALSE ELSE TRUE END AS transferido,
    CASE WHEN SC."Recontato" = 0 THEN FALSE ELSE TRUE END AS recontato,
    CASE WHEN SC."Respondido" = 0 THEN FALSE ELSE TRUE END AS respondido,
    CASE WHEN SC."Reaberto" = 0 THEN FALSE ELSE TRUE END AS reaberto,
    NOW() AS datainsercao,
    NOW() AS datamodificacao,
    SC."Comentario",
    SC."QuantidadeInteracoesKinghost" as quantidadeinteracoeskinghost
FROM kinghost.stgchamados SC
LEFT JOIN kinghost.chamadosbacklog BC
    ON SC."IdChamado" = BC.idefetivo
    and SC."QuantidadeInteracoesKinghost" = BC.quantidadeinteracoeskinghost
    and SC."QuantidadeInteracoesCliente" = BC.quantidadeinteracoescliente
WHERE BC.idefetivo IS NULL ;
