INSERT INTO kinghost.chamados
SELECT 
CAST("IdChamado" AS VARCHAR) AS idchamado,
"IdChamado" AS idefetivo,
"IdIncidente" AS idincidente,
substring("Fila" from '\((.*?)\)') AS categoriafila,
"Fila" AS fila,
"LoginCliente" AS logincliente,
"AbertoPor",
"Proprietario",
"EquipeProprietaria",
"Assunto",
"PrioridadeInicial",
"PrioridadeFinal",
"Prioridade",
"TipoContato",
"TempoEstimado",
"TempoTrabalhado",
initcap(substring("Status" from '\w+')) AS status,
"RazaoStatus",
"TempoRestante",
to_timestamp("DataRecebido") AT TIME ZONE 'America/Sao_Paulo' AS datarecebido,
NULL AS datainicio,
CAST("DataInicio" AS TIMESTAMP) AS datainiciado,
to_timestamp("DataRecebido") AT TIME ZONE 'America/Sao_Paulo' AS datadevida,
CAST("DataResolvido" AS TIMESTAMP) AS dataresolvido,
"AgenteUltimaInteracao",
CAST("DataUltimaInteracao" AS TIMESTAMP) AS dataultimainteracao,
"Criador",
CAST("DataCriacao" AS TIMESTAMP) AS datacriacao,
"P1",
"P2",
"P3",
"Canal",
initcap(substring("Origem" from '\w+')) AS origem,
CAST('KingHost' AS VARCHAR) AS fontedados,
"QuantidadeInteracoesKinghost" + "QuantidadeInteracoesCliente" AS quantidadeinteracoes,
"TemMotivo",
CASE WHEN "TemClassificacao" IS NULL THEN 'Não' ELSE "TemClassificacao" END AS temclassificacao,
"Nivel1",
"Nivel2",
"Nivel3",
NULL AS nivel4,
NULL AS nivel5,
"inc_ritm_prb",
"inc",
"ritm",
"prb",
CASE WHEN "Transferido" = 0 THEN FALSE ELSE TRUE END AS transferido,
CASE WHEN "Recontato" = 0 THEN FALSE ELSE TRUE END AS recontato,
CASE WHEN "Respondido" = 0 THEN FALSE ELSE TRUE END AS respondido,
CASE WHEN "Reaberto" = 0 THEN FALSE ELSE TRUE END AS reaberto,
NOW() AS datainsercao,
NOW() AS datamodificacao
FROM kinghost.stgchamados SC
WHERE NOT EXISTS (SELECT 1 FROM kinghost.chamados AS C WHERE SC."IdChamado" = C.idefetivo);