INSERT INTO lw_octadesk.stg_login_do_cliente
  (chat_id, login_usuario, customer_id, data_ultima_interacao, qtd_interacoes,motivo_de_contato,nivel1,nivel2,nivel3,nivel4,nivel5, fonte_de_dados, data_insercao, data_modificacao, lista_agentes,
  agente1,agente2,agente3,agente4,agente5,agente6,agente7,agente8,agente9,agente10,from_number,from_name,to_number)
 SELECT
  B.id::VARCHAR,
  NULLIF(BTRIM(B.login_usuario::text), '') AS login_usuario,
  NULLIF(BTRIM(B.customer_id::text), '')  AS customer_id,
  B.data_ultima_interacao,
  B.messages_count::INTEGER as qtd_interacoes,
  B.motivo_de_contato::VARCHAR as motivo_de_contato,
  NULLIF(TRIM(SPLIT_PART(REGEXP_REPLACE(B.motivo_de_contato, '[{}"\[\]\*]', '', 'g'), '>', 1)), '') AS nivel1,
  NULLIF(TRIM(SPLIT_PART(REGEXP_REPLACE(B.motivo_de_contato, '[{}"\[\]\*]', '', 'g'), '>', 2)), '') AS nivel2,
  NULLIF(TRIM(SPLIT_PART(REGEXP_REPLACE(B.motivo_de_contato, '[{}"\[\]\*]', '', 'g'), '>', 3)), '') AS nivel3,
  NULLIF(TRIM(SPLIT_PART(REGEXP_REPLACE(B.motivo_de_contato, '[{}"\[\]\*]', '', 'g'), '>', 4)), '') AS nivel4,
  NULLIF(TRIM(SPLIT_PART(REGEXP_REPLACE(B.motivo_de_contato, '[{}"\[\]\*]', '', 'g'), '>', 5)), '') AS nivel5,
  'Endpoint /chat/id' AS fonte_de_dados,
  NOW() AS data_insercao,
  NOW() AS data_modificacao,
  REGEXP_REPLACE(B.lista_agentes, '[\[\]\*]', '', 'g') AS lista_agentes,
  LOWER(B.agente1) AS agente1,
  LOWER(B.agente2) AS agente2,
  LOWER(B.agente3) AS agente3,
  LOWER(B.agente4) AS agente4,
  LOWER(B.agente5) AS agente5,
  LOWER(B.agente6) AS agente6,
  LOWER(B.agente7) AS agente7,
  LOWER(B.agente8) AS agente8,
  LOWER(B.agente9) AS agente9,
  LOWER(B.agente10) AS agente10,
  REGEXP_REPLACE(B.from_number, '[\[\]\*+]', '', 'g') AS from_number,
  REGEXP_REPLACE(from_name, '[^[:alnum:][:space:]]', '', 'g') AS from_name,
  REGEXP_REPLACE(B.to_number, '[\[\]\*+]', '', 'g') AS to_number
FROM lw_octadesk.rawdata_login_do_cliente B