-- DDL: tabelas para carga de Problems do Service-Now (rotina LWSA)
-- A tabela raw (lwsa.rawdata_service_now_problems) e criada/sobrescrita pelo pandas to_sql.

CREATE TABLE IF NOT EXISTS lwsa.stg_service_now_problems (
    numero               VARCHAR(50),
    organizacao          VARCHAR(255),
    task_for             VARCHAR(255),
    servidor             VARCHAR(255),
    grupo_designado      VARCHAR(255),
    designado_para       VARCHAR(255),
    prioridade           VARCHAR(50),
    produto              VARCHAR(255),
    categoria            VARCHAR(255),
    subcategoria         VARCHAR(255),
    status               VARCHAR(50),
    origem               VARCHAR(255),
    data_abertura        TIMESTAMP,
    aberto_por           VARCHAR(255),
    data_encerrado       TIMESTAMP,
    fechado_por          VARCHAR(255),
    codigo_encerramento  VARCHAR(255),
    chamado_externo      VARCHAR(255),
    prb_revisado         VARCHAR(50),
    descricao_curta      TEXT,
    descricao            TEXT,
    solucao_alternativa  TEXT,
    fechamento           TEXT,
    atualizacoes         INTEGER,
    id_departamento      VARCHAR(50),
    tipo_usuario         VARCHAR(50),
    fonte_de_dados       VARCHAR(255),
    data_insercao        TIMESTAMP,
    data_modificacao     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lwsa.service_now_problems (
    numero               VARCHAR(50) PRIMARY KEY,
    organizacao          VARCHAR(255),
    task_for             VARCHAR(255),
    servidor             VARCHAR(255),
    grupo_designado      VARCHAR(255),
    designado_para       VARCHAR(255),
    prioridade           VARCHAR(50),
    produto              VARCHAR(255),
    categoria            VARCHAR(255),
    subcategoria         VARCHAR(255),
    status               VARCHAR(50),
    origem               VARCHAR(255),
    data_abertura        TIMESTAMP,
    aberto_por           VARCHAR(255),
    data_encerrado       TIMESTAMP,
    fechado_por          VARCHAR(255),
    codigo_encerramento  VARCHAR(255),
    chamado_externo      VARCHAR(255),
    prb_revisado         VARCHAR(50),
    descricao_curta      TEXT,
    descricao            TEXT,
    solucao_alternativa  TEXT,
    fechamento           TEXT,
    atualizacoes         INTEGER,
    id_departamento      VARCHAR(50),
    tipo_usuario         VARCHAR(50),
    fonte_de_dados       VARCHAR(255),
    data_insercao        TIMESTAMP,
    data_modificacao     TIMESTAMP
);