INSERT INTO octadesk.ticketsbacklog
SELECT 
id ,
numero ,
datacriacao ,
assunto ,
status_id ,
status ,
canal_id ,
canal ,
aberto_por_id ,
aberto_por_nome ,
aberto_por_email ,
grupo_id ,
grupo ,
prioridade_id ,
prioridade ,
organizacao_id ,
organizacao ,
atribuido_id ,
atribuido_lista ,
ultimo_analista_id,
ultimo_analista_nome,
tags ,
tag_1 ,
tag_2 ,
tag_3 ,
tag_4 ,
tag_5 ,
qtd_interacoes ,
data_atualizacao ,
atualizado_por_id ,
atualizado_por_nome ,
atualizado_por_email ,
ultima_interacao_id ,
ultima_interacao_canal ,
ultima_interacao_nome ,
ultima_interacao_email ,
ultima_interacao_organizacao ,
ultima_interacao_status ,
ultima_interacao_form ,
ultima_interacao_conteudo ,
ultima_interacao_humana_id ,
ultima_interacao_humana_canal ,
ultima_interacao_humana_nome ,
ultima_interacao_humana_email ,
ultima_interacao_humana_organizacao ,
ultima_interacao_humana_status ,
ultima_interacao_humana_form,
'API tickets' AS fonte_de_dados,
NOW() AS data_insercao,
NOW() AS data_modificacao
FROM octadesk.stgtickets SI
WHERE NOT EXISTS (
    SELECT 1 
    FROM octadesk.ticketsbacklog AS I 
    WHERE SI.numero = I.numero AND 	SI.data_atualizacao = I.data_atualizacao
)