INSERT INTO octadesk.stgtickets (
    id ,
    numero ,
    datacriacao ,
    assunto ,
    status_id ,
    status ,
    canal_id ,
    canal ,
    aberto_por_id ,
    aberto_por_nome ,
    aberto_por_email ,
    grupo_id ,
    grupo ,
    prioridade_id ,
    prioridade ,
    organizacao_id ,
    organizacao ,
    atribuido_id ,
    atribuido_lista ,
    ultimo_analista_id,
    ultimo_analista_nome,
    tags ,
    tag_1 ,
    tag_2 ,
    tag_3 ,
    tag_4 ,
    tag_5 ,
    qtd_interacoes ,
    data_atualizacao ,
    atualizado_por_id ,
    atualizado_por_nome ,
    atualizado_por_email ,
    ultima_interacao_id ,
    ultima_interacao_canal ,
    ultima_interacao_nome ,
    ultima_interacao_email ,
    ultima_interacao_organizacao ,
    ultima_interacao_status ,
    ultima_interacao_form ,
    ultima_interacao_conteudo ,
    ultima_interacao_humana_id ,
    ultima_interacao_humana_canal ,
    ultima_interacao_humana_nome ,
    ultima_interacao_humana_email ,
    ultima_interacao_humana_organizacao ,
    ultima_interacao_humana_status ,
    ultima_interacao_humana_form 
    )
    SELECT 
t.id::VARCHAR AS id,
t.number::INTEGER AS numero,
t.created_at::TIMESTAMP AS datacriacao,
t.summary::text AS assunto,
t.status_id::VARCHAR AS status_id,
t.status_name::VARCHAR AS status,
t.channel_id::VARCHAR AS canal_id,
NULLIF(REGEXP_REPLACE(t.channel_name::VARCHAR, '[{}]','','g'),'') AS canal,
t.requester_id::VARCHAR AS aberto_por_id,
NULLIF(REGEXP_REPLACE(t.requester_name::VARCHAR, '[{}]','','g'),'') AS aberto_por_nome,
NULLIF(REGEXP_REPLACE(t.requester_email::VARCHAR, '[{}]','','g'),'') AS aberto_por_email,
t.group_id::VARCHAR AS grupo_id,
NULLIF(REGEXP_REPLACE(t.group_name::VARCHAR, '[{}]','','g'),'') AS grupo,
t.priority_id::VARCHAR AS prioridade_id,
NULLIF(REGEXP_REPLACE(t.priority_name::VARCHAR, '[{}]','','g'),'') AS prioridade,
t.organization_id::VARCHAR AS organizacao_id,
NULLIF(REGEXP_REPLACE(t.organization_name::VARCHAR, '[{}]','','g'),'') AS organizacao,
t.assigned_id::VARCHAR AS atribuido_id,
participating_assigned::JSON AS atribuido_lista,
participating_assigned_id::VARCHAR AS ultimo_analista_id,
participating_assigned_name::VARCHAR AS ultimo_analista_nome,
NULLIF(REGEXP_REPLACE(tags, '[{}\[\]]', '', 'g'),'') AS tags,
NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"\[\]]', '', 'g'), ',', 1)), '') AS tag_1,
NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"\[\]]', '', 'g'), ',', 2)), '') AS tag_2,
NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"\[\]]', '', 'g'), ',', 3)), '') AS tag_3,
NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"\[\]]', '', 'g'), ',', 4)), '') AS tag_4,
NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"\[\]]', '', 'g'), ',', 5)), '') AS tag_5,
t.interactions_count::INTEGER AS qtd_interacoes,
t.update_at::TIMESTAMP AS data_atualizacao,
t.update_by_id::VARCHAR AS atualizado_por_id,
t.update_by_name::VARCHAR AS atualizado_por_nome,
t.update_by_email::VARCHAR AS atualizado_por_email,
t.li_id::VARCHAR AS ultima_interacao_id,
NULLIF(REGEXP_REPLACE(t.li_properties_changes_channel::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_canal,
NULLIF(SPLIT_PART(REGEXP_REPLACE(t.li_properties_changes_requester::VARCHAR,'[{}"]','','g'), ' (', 1),'') AS ultima_interacao_nome,
NULLIF(SPLIT_PART(SPLIT_PART(REGEXP_REPLACE(t.li_properties_changes_requester::VARCHAR,'[{}"]','','g'), '(', 2), ')', 1),'') AS ultima_interacao_email,
NULLIF(REGEXP_REPLACE(t.li_properties_changes_organization::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_organizacao,
NULLIF(REGEXP_REPLACE(t.li_properties_changes_status::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_status,
NULLIF(REGEXP_REPLACE(t.li_properties_changes_form::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_form,
t.li_comments::JSON AS ultima_interacao_conteudo,
t.li_id::VARCHAR AS ultima_interacao_humana_id,
NULLIF(REGEXP_REPLACE(t.lhi_properties_changes_channel::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_humana_canal,
NULLIF(SPLIT_PART(REGEXP_REPLACE(t.lhi_properties_changes_requester::VARCHAR,'[{}"]','','g'), ' (', 1),'') AS ultima_interacao_humana_nome,
NULLIF(SPLIT_PART(SPLIT_PART(REGEXP_REPLACE(t.lhi_properties_changes_requester::VARCHAR,'[{}"]','','g'), '(', 2), ')', 1),'') AS ultima_interacao_humana_email,
NULLIF(REGEXP_REPLACE(t.lhi_properties_changes_organization::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_humana_organizacao,
NULLIF(REGEXP_REPLACE(t.lhi_properties_changes_status::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_humana_status,
NULLIF(REGEXP_REPLACE(t.lhi_properties_changes_form::VARCHAR, '[{}"]', '', 'g'),'') AS ultima_interacao_humana_form
FROM octadesk.rawdata_tickets t

