INSERT INTO kinghost.chamadosbacklog (
    idchamado,
    idefetivo,
    idcliente,
    categoriafila,
    fila,
    logincliente,
    abertopor,
    proprietario,
    equipeproprietaria,
    assunto,
    prioridadeinicial,
    prioridadefinal,
    prioridade,
    status,
    datainiciado,
    dataresolvido,
    agenteultimainteracao,
    dataultimainteracao,
    criador,
    datacriacao,
    p1,
    p2,
    p3,
    comentarios,
    canal,
    origem,
    fontedados,
    quantidadedeinteracoeskinghost,
    quantidadedeinteracoescliente,
    quantidadeinteracoes,
    temmotivo,
    temclassificacao,
    nivel1,
    nivel2,
    nivel3,
    nivel4,
    nivel5,
    inc_ritm_prb,
    inc,
    ritm,
    prb,
    transferido,
    recontato,
    respondido,
    reaberto,
    datainsercao,
    datamodificacao,
    analista
)
SELECT 
    CAST(SC."idChamado" AS VARCHAR) AS idchamado,
    SC."idChamado" AS idefetivo,
    SC."idCliente" AS idcliente,
    substring(SC."Fila" from '\((.*?)\)') AS categoriafila,
    REPLACE(REPLACE(SC."Fila", '(', ''), ')', '') AS fila,
    SC."LoginCliente" AS logincliente,
    SC."AbertoPor" AS abertopor,
    SC."Proprietario" AS proprietario,
    SC."EquipeProprietaria" AS equipeproprietaria,
    SC."Assunto" AS assunto,
    SC."PrioridadeInicial" AS prioridadeinicial,
    SC."PrioridadeFinal" AS prioridadefinal,
    SC."Prioridade" AS prioridade,
    initcap(substring(SC."StatusChamado" from '\w+')) AS status,
    CAST(SC."DataInicio" AS TIMESTAMP) AS datainiciado,
    CAST(SC."DataResolvido" AS TIMESTAMP) AS dataresolvido,
    SC."AgenteUltimaInteracao" AS agenteultimainteracao,
    CAST(SC."DataUltimaInteracao" AS TIMESTAMP) AS dataultimainteracao,
    SC."Criador" AS criador,
    CAST(SC."DataCriacaoChamado" AS TIMESTAMP) AS datacriacao,
    SC."P1" AS p1,
    SC."P2" AS p2,
    SC."P3" AS p3,
    SC."Comentario" AS comentarios,
    'Chamados' AS canal,
    initcap(substring(SC."Origem" from '\w+')) AS origem,
    CAST('KingHost' AS VARCHAR) AS fontedados,
    CASE 
        WHEN SC."AgenteUltimaInteracao" NOTNULL THEN 1
        ELSE 0 
    END AS quantidadedeinteracoeskinghost,
    CASE 
        WHEN SC."AgenteUltimaInteracao" IS NULL THEN 1
        ELSE 0
    END AS quantidadedeinteracoescliente,
    1 AS quantidadeinteracoes,
    SC."TemMotivo" AS temmotivo,
    CASE WHEN SC."TemClassificacao" IS NULL THEN 'Não' ELSE SC."TemClassificacao" END AS temclassificacao,
    SC."Nivel1" AS nivel1,
    SC."Nivel2" AS nivel2,
    SC."Nivel3" AS nivel3,
    NULL AS nivel4,
    NULL AS nivel5,
    SC."inc_ritm_prb" AS inc_ritm_prb,
    SC."inc" AS inc,
    SC."ritm" AS ritm,
    SC."prb" AS prb,
    CASE WHEN SC."Transferido" = 0 THEN FALSE ELSE TRUE END AS transferido,
    CASE WHEN SC."Recontato" = 0 THEN FALSE ELSE TRUE END AS recontato,
    CASE WHEN SC."Respondido" = 0 THEN FALSE ELSE TRUE END AS respondido,
    CASE WHEN SC."Reaberto" = 0 THEN FALSE ELSE TRUE END AS reaberto,
    NOW() AS datainsercao,
    NOW() AS datamodificacao,
    SC."Analista" AS analista
FROM kinghost.stgchamadosking SC
WHERE NOT EXISTS (SELECT 1 FROM kinghost.chamadosbacklog C WHERE SC."idChamado" = C.idefetivo and SC."DataUltimaInteracao"::TIMESTAMP = C.dataultimainteracao);