INSERT INTO octadesk.tickets_detalhados
(
    number,
    id,
    summary,
    description,
    status_id,
    status_name,
    channel_id,
    channel_name,
    requester_id,
    requester_name,
    requester_email,
    requester_custom_fields,
    requester_cf_id_contact_status,
    requester_cf_cnpj,
    requester_cf_chat_id_conversa,
    requester_cf_chat_subdominio_octadesk,
    requester_cf_chat_ultima_data_contato,
    requester_cf_chat_id_ultima_conversa,
    requester_cf_chat_nome_grupo_atendimento,
    requester_cf_chat_tem_ticket,
    requester_cf_cluster,
    requester_cf_codigo_do_plano,
    requester_cf_mrr,
    requester_cf_data_de_contratacao,
    requester_cf_perfil_do_usuario,
    group_id,
    group_name,
    form_id,
    form_name,
    priority_id,
    priority_name,
    custom_fields_organization,
    assigned_id,
    assigned_name,
    assigned_email,
    participating_assigned,
    last_id,
    last_name,
    cc,
    cco,
    tags,
    interactions_count,
    created_at,
    updated_at,
    updated_by_id,
    updated_by_name,
    updated_by_email,
    custom_field,
    cf_quem_interagiu_por_ultimo,
    cf_squad,
    cf_ambiente,
    cf_cluster,
    cf_status_do_card_no_jira,
    cf_tipo_do_ticket_produto,
    cf_escalado_n3,
    cf_reputacao_afetada,
    cf_nivel_de_atrito,
    cf_risco_de_churn_oficial,
    cf_analista_responsavel_pela_abertura,
    cf_whatsapp_do_cliente,
    cf_an_lise_qualidade,
    cf_analise_qualidade,
    apps,
    last_interaction,
    last_human_interaction,
    attachments,
    fonte_de_dados,
    data_insercao,
    data_modificacao,
    resolution_at
)
SELECT
    a.number::INTEGER AS number,
    a.id::VARCHAR AS id,
    NULLIF(a.summary::TEXT, '') AS summary,
    NULLIF(a.description::TEXT, '') AS description,
    NULLIF(a.status_id::VARCHAR, '') AS status_id,
    NULLIF(a.status_name::VARCHAR, '') AS status_name,
    NULLIF(a.channel_id::VARCHAR, '') AS channel_id,
    NULLIF(a.channel_name::VARCHAR, '') AS channel_name,
    NULLIF(a.requester_id::VARCHAR, '') AS requester_id,
    NULLIF(a.requester_name::VARCHAR, '') AS requester_name,
    NULLIF(a.requester_email::VARCHAR, '') AS requester_email,
    NULLIF(a.requester_custom_fields::TEXT, '') AS requester_custom_fields, 
    NULLIF(a.requester_cf_id_contact_status::VARCHAR, '') AS requester_cf_id_contact_status,
    NULLIF(a.requester_cf_cnpj::VARCHAR, '') AS requester_cf_cnpj,
    NULLIF(a.requester_cf_chat_id_conversa::VARCHAR, '') AS requester_cf_chat_id_conversa,
    NULLIF(a.requester_cf_chat_subdominio_octadesk::VARCHAR, '') AS requester_cf_chat_subdominio_octadesk,
    a.requester_cf_chat_ultima_data_contato::TIMESTAMP AS requester_cf_chat_ultima_data_contato,
    NULLIF(a.requester_cf_chat_id_ultima_conversa::VARCHAR, '') AS requester_cf_chat_id_ultima_conversa,
    NULLIF(a.requester_cf_chat_nome_grupo_atendimento::VARCHAR, '') AS requester_cf_chat_nome_grupo_atendimento,
    NULLIF(a.requester_cf_chat_tem_ticket::VARCHAR, '') AS requester_cf_chat_tem_ticket,
    NULLIF(a.requester_cf_cluster::VARCHAR, '') AS requester_cf_cluster,
    NULLIF(a.requester_cf_codigo_do_plano::VARCHAR, '') AS requester_cf_codigo_do_plano,
    NULLIF(REPLACE(REGEXP_REPLACE(a.requester_cf_mrr::VARCHAR, '[^0-9,]', '', 'g'),',', '.'), '')::FLOAT AS requester_cf_mrr,
    CASE
        WHEN a.requester_cf_data_de_contratacao ~ '^\d{2}/\d{2}/\d{4}$' THEN 
            TO_DATE(a.requester_cf_data_de_contratacao, 'DD/MM/YYYY')
        WHEN a.requester_cf_data_de_contratacao ~ '^\d{2}\.\d{2}\.\d{4}$' THEN 
            TO_DATE(a.requester_cf_data_de_contratacao, 'DD.MM.YYYY')
        ELSE NULL
    END AS requester_cf_data_de_contratacao,
    NULLIF(a.requester_cf_perfil_do_usuario::VARCHAR, '') AS requester_cf_perfil_do_usuario,
    NULLIF(a.group_id::VARCHAR, '') AS group_id,
    NULLIF(a.group_name::VARCHAR, '') AS group_name,
    NULLIF(a.form_id::VARCHAR, '') AS form_id,
    NULLIF(a.form_name::VARCHAR, '') AS form_name,
    NULLIF(a.priority_id::VARCHAR, '') AS priority_id,
    NULLIF(a.priority_name::VARCHAR, '') AS priority_name,
    NULLIF(a.custom_fields_organization::TEXT, '') AS custom_fields_organization,
    NULLIF(a.assigned_id::VARCHAR, '') AS assigned_id,
    NULLIF(a.assigned_name::VARCHAR, '') AS assigned_name,
    NULLIF(a.assigned_email::VARCHAR, '') AS assigned_email,
    NULLIF(a.participating_assigned::TEXT, '') AS participating_assigned,
    NULLIF(a.last_id::VARCHAR, '') AS last_id,
    NULLIF(a.last_name::VARCHAR, '') AS last_name,
    NULLIF(a.cc::TEXT, '') AS cc,
    NULLIF(a.cco::TEXT, '') AS cco,
    NULLIF(a.tags::TEXT, '') AS tags,
    a.interactions_count::INTEGER AS interactions_count,
    a.created_at::TIMESTAMP AS created_at,
    a.updated_at::TIMESTAMP AS updated_at,
    NULLIF(a.updated_by_id::VARCHAR, '') AS updated_by_id,
    NULLIF(a.updated_by_name::VARCHAR, '') AS updated_by_name,
    NULLIF(a.updated_by_email::VARCHAR, '') AS updated_by_email,
    NULLIF(a.custom_field::TEXT, '') AS custom_field,
    NULLIF(a.cf_quem_interagiu_por_ultimo::VARCHAR, '') AS cf_quem_interagiu_por_ultimo,
    NULLIF(a.cf_squad::VARCHAR, '') AS cf_squad,
    NULLIF(a.cf_ambiente::VARCHAR, '') AS cf_ambiente,
    NULLIF(a.cf_cluster::VARCHAR, '') AS cf_cluster,
    NULLIF(a.cf_status_do_card_no_jira::VARCHAR, '') AS cf_status_do_card_no_jira,
    NULLIF(a.cf_tipo_do_ticket_produto::VARCHAR, '') AS cf_tipo_do_ticket_produto,
    CASE 
    	WHEN a.cf_escalado_n3::BOOLEAN IS NULL THEN FALSE 
    	ELSE a.cf_escalado_n3::BOOLEAN
    END AS cf_escalado_n3,
    NULLIF(a.cf_reputacao_afetada::VARCHAR, '') AS cf_reputacao_afetada,
    NULLIF(a.cf_nivel_de_atrito::VARCHAR, '') AS cf_nivel_de_atrito,
    NULLIF(a.cf_risco_de_churn_oficial::VARCHAR, '') AS cf_risco_de_churn_oficial,
    NULLIF(a.cf_analista_responsavel_pela_abertura::VARCHAR, '') AS cf_analista_responsavel_pela_abertura,
    NULLIF(a.cf_whatsapp_do_cliente::VARCHAR, '') AS cf_whatsapp_do_cliente,
    NULLIF(a.cf_an_lise_qualidade::VARCHAR, '') AS cf_an_lise_qualidade,
    NULLIF(a.cf_analise_qualidade::VARCHAR, '') AS cf_analise_qualidade,
    NULLIF(a.apps::TEXT, '') AS apps,
    NULLIF(a.last_interaction::TEXT, '') AS last_interaction,
    NULLIF(a.last_human_interaction::TEXT, '') AS last_human_interaction,
    NULLIF(a.attachments::TEXT, '') AS attachments,
    'API Pública - Endpoint /tickets/{id}' AS fonte_de_dados,
    NOW() AS data_insercao,
    NOW() AS data_modificacao,
    a.resolution_Date::TIMESTAMP AS resolution_at
FROM octadesk.rawdata_tickets_detalhes a
WHERE NOT EXISTS (
    SELECT 1 
    FROM octadesk.tickets_detalhados AS b 
    WHERE a.number = b.number 
    AND a.updated_at::TIMESTAMP = b.updated_at::TIMESTAMP
)
