INSERT INTO kinghost_octadesk.stgchat
(id,protocolo,
agent_id,
agent_name,
agent_email,
canal,
data_inicio_interacao,
data_ultima_interacao,
data_fim_interacao,
tempo_atendimento_segundos,
tempo_atendimento_formatado, 
contact_name,
contact_id,
iniciado_por,
tags,
tag_1,
tag_2,
tag_3,
tag_4,
tag_5,
tag_6,
tag_7,
tag_8,
com_bot,
status,
grupo_id,
grupo_nome,
nao_lidas,
tempo_espera,
tempo_atendimento_analista,
origem,
status_detail,
data_inicio_interacao_agente,
atribuicao_agente,
atribuicao_grupo,
pesquisa,
comentario,
fonte_de_dados,
data_insercao,
data_modificacao
)
SELECT 
    distinct
    id::VARCHAR,
    protocolo::BIGINT,
    agent_id::VARCHAR,
    LOWER(NULLIF(agent_name::VARCHAR, '')) AS agent_name,
    NULLIF(agent_email::VARCHAR, '') AS agent_email,
    canal::VARCHAR,
	data_inicio_interacao::TIMESTAMP(0) AS data_inicio_interacao,
    data_ultima_interacao::TIMESTAMP,
    data_fim_interacao::TIMESTAMP, 
    EXTRACT(EPOCH FROM (CAST(data_fim_interacao AS TIMESTAMP) - CAST(atribuicao_agente AS TIMESTAMP))) AS tempo_atendimento_segundos,
    (CAST(data_fim_interacao AS TIMESTAMP) - CAST(atribuicao_agente AS TIMESTAMP)) AS tempo_atendimento_formatado,
    CASE 
        WHEN LENGTH(contact_name) > 255 THEN NULL 
        ELSE REGEXP_REPLACE(contact_name, '[^\u0000-\u007F]', '', 'g')
    END AS contact_name,
    CASE 
        WHEN LENGTH(contact_id) < 4 THEN NULL 
        ELSE contact_id
    END AS contact_id,
    CASE 
        WHEN REGEXP_REPLACE(contact_name, '[^\u0000-\u007F]', '', 'g') = agent_name THEN 'kinghost_octadesk'
        ELSE 'Cliente'
    END AS iniciado_por,
    tags::TEXT ,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 1)), '') AS tag_1,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 2)), '') AS tag_2,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 3)), '') AS tag_3,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 4)), '') AS tag_4,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 5)), '') AS tag_5,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 6)), '') AS tag_6,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 7)), '') AS tag_7,
    NULLIF(UPPER(SPLIT_PART(REGEXP_REPLACE(tags, '[{}"]', '', 'g'), ',', 8)), '') AS tag_8,
    com_bot::BOOLEAN,
    status::VARCHAR,
    grupo_id::VARCHAR,
    grupo_nome::VARCHAR,
    nao_lidas::BOOLEAN,
    EXTRACT(EPOCH FROM (CAST(atribuicao_agente AS TIMESTAMP) - CAST(atribuicao_grupo AS TIMESTAMP))) AS tempo_espera,
    EXTRACT(EPOCH FROM (CAST(data_fim_interacao AS TIMESTAMP) - CAST(data_inicio_interacao_agente AS TIMESTAMP))) AS tempo_atendimento_analista,
    origem::VARCHAR,
    status_detail::VARCHAR,
    data_inicio_interacao_agente::TIMESTAMP,
    atribuicao_agente::TIMESTAMP,
    atribuicao_grupo::TIMESTAMP,
    pesquisa::VARCHAR,
    NULLIF(comentario::TEXT, '') AS comentario,
    'API Pública - Endpoint /chat' AS fonte_de_dados,
    NOW() AS data_insercao,
    NOW() AS data_modificacao
FROM kinghost_octadesk.rawdata_chat r;
